// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdVTI_Qz4LJa_RTwUob-6gqOBqfdoRIM0',
    appId: '1:331235515879:web:41f2f6833f34b409247142',
    messagingSenderId: '331235515879',
    projectId: 'instant-language',
    authDomain: 'instant-language.firebaseapp.com',
    storageBucket: 'instant-language.appspot.com',
    measurementId: 'G-NFKJTM4QKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMLzEsFOTfsO20PwIn-uJNqGs_iP4l6bw',
    appId: '1:331235515879:android:77cf885e2f916636247142',
    messagingSenderId: '331235515879',
    projectId: 'instant-language',
    storageBucket: 'instant-language.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuwLmdgR90K1FCJAHmWnu1UDforMLK7oo',
    appId: '1:331235515879:ios:396c1e6e3fede5a1247142',
    messagingSenderId: '331235515879',
    projectId: 'instant-language',
    storageBucket: 'instant-language.appspot.com',
    iosBundleId: 'com.example.instantLanguageTrans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuwLmdgR90K1FCJAHmWnu1UDforMLK7oo',
    appId: '1:331235515879:ios:396c1e6e3fede5a1247142',
    messagingSenderId: '331235515879',
    projectId: 'instant-language',
    storageBucket: 'instant-language.appspot.com',
    iosBundleId: 'com.example.instantLanguageTrans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdVTI_Qz4LJa_RTwUob-6gqOBqfdoRIM0',
    appId: '1:331235515879:web:733ae169b1da0414247142',
    messagingSenderId: '331235515879',
    projectId: 'instant-language',
    authDomain: 'instant-language.firebaseapp.com',
    storageBucket: 'instant-language.appspot.com',
    measurementId: 'G-1KRKSBKHZ7',
  );
}
